fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-yaml
        exclude: \.gitlab-ci\.yml

      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black src
        pass_filenames: false
        language: system

      - id: isort
        name: isort
        entry: poetry run isort src
        pass_filenames: false
        language: system

      - id: flake8
        name: flake8
        entry: poetry run flake8p src
        pass_filenames: false
        language: system

      - id: pylint
        name: pylint
        entry: poetry run pylint src
        language: system
        pass_filenames: false

      - id: strict-flake8
        name: strict-flake8
        entry: poetry run flake8p src
        additional_dependencies:
          [
            pyproject-flake8,
            flake8-eradicate,
            flake8-boolean-trap,
            flake8-print,
            wemake-python-styleguide,
          ]
        pass_filenames: false
        language: python

      - id: mypy
        name: mypy
        entry: poetry run mypy src
        pass_filenames: false
        language: system

      - id: pytest
        name: pytest
        entry: poetry run pytest --cov=src --cov-report=term-missing --cov-fail-under=80
        pass_filenames: false
        language: system
